### ISSUE TITLE
Intenta no usar rutas absolutas

### ISSUE THREAD

**Issue by kretinoh** [JoseLafuenteColorado/calculadora#1]
Referencia: https://github.com/JoseLafuenteColorado/calculadora/blob/330f95d363812b197b8460629d520c5af5af3155/calculadora.py#L84

Buenos días si me permites te agrego este issue.
Si alguien quisiera usar este programa para ejecutarlo en su máquina no le cargaría ese elemento ya que está en una ruta absoluta.
En su lugar intenta usar siempre rutas relativas.

### Cargar la imagen desde la carpeta "img"
```python
image_path = "img/imagen.png"  # Ruta de la imagen en la carpeta "img"
img = Image.open(image_path)
photo = ImageTk.PhotoImage(img)
```

### Mostrar la imagen en un widget Label
```python
label = tk.Label(root, image=photo)
label.pack()
```
Sigue así

**Comment by JoseLafuenteColorado** [comment]
Corregido, muchas gracias.
